apiVersion: v1
kind: ConfigMap
metadata:
  name: todoappfrontend-config
data:
  # The frontend targets the Next.js backend by default which goes through the gateway and gets rerouted to api backend depending on path
  NEXT_PUBLIC_API_URL: ""
  BACKEND_SERVICE_URL: "http://todoapp-backend-svc:3001"
  BACKEND_READY_PATH: "/ready"
  DYN_ASSET_DIR_PATH: "./dynamic"
  IMAGE_FETCH_URL: "https://picsum.photos/1200"
  IMAGE_DIR_NAME: "images"
  IMAGE_NAME: "image.jpg"
  IMAGE_FETCH_TIMEOUT: "600000"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: todoappbackend-config
data:
  #Port needs to be exposed during Docker build so basically needs to be pre-configured before the Kubernetes manifest configuration
  PORT: "3001"
  TODO_MIN_LENGTH: "1"
  TODO_MAX_LENGTH: "140"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: todoappapiroutes-config
data:
  API_PATH: "/api"
