apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: broadcaster-dep
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: PROJECT/BROADCASTERIMAGE
          env:
            - name: EXTERNAL_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-discord-webhook-config
                  key: EXTERNAL_SERVICE_URL
          envFrom:
            - configMapRef:
                name: nats-config
            - configMapRef:
                name: broadcaster-config