apiVersion: v1
kind: Secret
metadata:
    name: secret-postgres-config
    # 3.7: The namespace is set as part of the deployment pipeline. If setting with apply -n the namespace set in the file will conflict instead of being overwritten.
# The secret is not deployed with kustomization.yaml to avoid saving it to disk so cannot be overwritten with kustomization file namespace.
# The options are to remove the explicit namespace from the file so it can be set with the -n flag or use yq which github ubuntu runners have installed by default for modifying the yaml.
# namespace: project
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8y05lO92x+TRej1F1ihtog==,iv:doZDPYtDUnI8own6CHDGHGzPgJEOcbxo2mfcI0QQv5k=,tag:5JB401L7cMIEEg1JfsArlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaE1uazN4V1dwa1BuUVFi
            UkNtNmR3am1uNFBRN2szQWhrczJrdVNtYXdBCkdsTzdqVkJsMkcvNW1JQndrZDkx
            U0dRVDhjMEprTlBmWEF1aWpiV3ptS3cKLS0tIDBZOXRBZ0tpY3Z6QXFMYktNdU1t
            V3hMbmU0cjVrNTdhYVVsb1NhQ0RIOHMKA+mlPWe2nKBqIeyfJmsdzYaIdJerY/ux
            JEtFJw0p7aKQCiBg3Qd3C3rDeVahU4bEMK16UT8pg3e1SWvQc5AO/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age139unmlpzkn46je6z0ffy6d2lf49sffzsrldmj5xrh89chrku5u5skkh8at
    encrypted_regex: ^(data)$
    lastmodified: "2026-08-25T15:34:47Z"
    mac: ENC[AES256_GCM,data:wZezIBee95hbVBqyoVQ5FcY1YOLiqH7EBBJKfY/9z8bfkdBEynU+Dmk6b/GtImZXinTJXav1n5yBwMESDTTrG4uRcr5VmpLcFZVLn60HORloyyLZzhn8EUFD65gZfDfP7j0tbOCr0yg/poT+ylZhJ3HVcC0ar4IeVQMh5q4Gowc=,iv:9lzYHZHgY7fl+CLkAFZv5o4GYmiCXJFaB4DxS4kJsGQ=,tag:M9LYm5WlpV/24gAvUb+fUQ==,type:str]
    version: 3.13.3
