# Health check configuration for the load balancer. For more information
# about the fields, see https://cloud.google.com/compute/docs/reference/rest/v1/healthChecks.
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: frontend-healthcheck
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: todoapp-frontend-svc

---

apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: backend-healthcheck
  namespace: project
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /health
  targetRef:
    group: ""
    kind: Service
    name: todoapp-backend-svc
