apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikipedia-todo
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wikipedia-todo
            image: PROJECT/WIKIPEDIATODOJOBIMAGE
            resources:
              limits:
                cpu: "100m"
                memory: "150Mi"
            env:
              - name: WIKIPEDIA_URL
                value: "https://en.wikipedia.org/wiki/Special:Random"
              - name: POST_TODO_URL
                value: "http://todoapp-backend-svc:3001/todos"
          restartPolicy: OnFailure