apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todoapp-claim # name of the volume claim, this will be used in the deployment
spec:
  # 3.5: Google Kubernetes Engine will automatically provision a persistent disk for your PersistentVolumeClaim - just don't set the storage class.
  # Uncomment for local use
  storageClassName: sc-todoapp-staging-pv # this is the name of the persistent volume we are claiming