apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummysite-controller
images:
  - name: DUMMYSITECONTROLLER
    newName: hinichijou/dummysite_controller:cwh7ly63
resources:
  - manifests/deployment_controller_dummysite.yaml