apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummysite-controller
images:
- digest: sha256:27ac58d9e8568c3c7ab63ccb08c28f785b062a76895eccd99faf947fbc31c40a
  name: DUMMYSITECONTROLLER
  newName: hinichijou/dummysite_controller
resources:
- manifests/deployment_controller_dummysite.yaml
