apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-production
# Seems to cause potential issues
# namePrefix: prod-
resources:
- resources/sealed_secret_postgres_production.yaml
- resources/route_frontend_prod.yaml
- resources/route_backend_prod.yaml
- ./../../base
patches:
- path: patches/persistentvolumeclaim_todoapp_prod.yaml
- path: patches/configmap_todoapp_prod.yaml
images:
- digest: sha256:da4eed64808634ee727da54fc13c8028050f9e97fee473bf041130975db1c2fa
  name: PROJECT/BACKENDIMAGE
  newName: hinichijou/todo_app_backend-production
- digest: sha256:0e840bafa10fe503ab4f87e82d3b0c54881ca81c5b69a7690008a426ac28bcf4
  name: PROJECT/BROADCASTERIMAGE
  newName: hinichijou/broadcaster-production
- digest: sha256:81d4a8b61061c5466bfc2d68431315fe0e1cac2e7b09578212d657bddbb1d071
  name: PROJECT/DBBACKUPJOBIMAGE
  newName: hinichijou/db_backup_job-production
- digest: sha256:e185d3e80c39e0f2466126e416672b3bf73736cfd13ac1ef104518fb1acaba88
  name: PROJECT/FRONTENDIMAGE
  newName: hinichijou/todo_app_frontend-production
- digest: sha256:ab86903d8b9e71941da0f0b67ad2a6fe0ed5df3ee70b423b88709865fdc3482b
  name: PROJECT/WIKIPEDIATODOJOBIMAGE
  newName: hinichijou/wikipedia_todo_job-production
