apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummysite
configurations:
- manifests/dummysitekind.yaml
images:
- digest: sha256:01eafc7c49c3533a72730e72845f13385a5dfa4c25d03b4bdf208ef527e06494
  name: DUMMYSITE
  newName: hinichijou/dummysite
resources:
- manifests/dummysite.yaml
