apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummysite
configurations:
- manifests/dummysitekind.yaml
images:
- digest: sha256:2a30a5d6084a00fe5ffef0092601e2cbdc0db35cf2291dce412c3a8617dcf10a
  name: DUMMYSITE
  newName: hinichijou/dummysite
resources:
- manifests/dummysite.yaml
