apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummysite
configurations:
- manifests/dummysitekind.yaml
images:
- digest: sha256:17bfedd4e77b0b6b7bd562e99514dee7e6d3d3fa80376f56cd832b3c2aef5733
  name: DUMMYSITE
  newName: hinichijou/dummysite
resources:
- manifests/dummysite.yaml
