apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: argocd
  name: argocd-route
spec:
  parentRefs:
  - name: infra-gateway
    namespace: infra
    sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /argocd
    backendRefs:
    - name: argocd-server
      port: 80