apiVersion: v1
kind: ConfigMap
metadata:
  name: logoutput-config
  namespace: exercises
data:
  MESSAGE: "hello world"
  PING_PONG_APP_URL: "http://pingpongapp-svc:2345"
  PING_PONG_APP_PINGS_PATH: "/pings"
  PING_PONG_APP_READY_PATH: "/ready"