apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Claims can have a namespace i.e. persistent volumes can be claimed from multiple namespaces
  namespace: exercises
  name: log-output-claim # name of the volume claim, this will be used in the deployment
spec:
  # 3.1: Google Kubernetes Engine will automatically provision a persistent disk for your PersistentVolumeClaim - just don't set the storage class. Uncomment for local use.
  storageClassName: sc-log-output-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi