---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: exercises
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBwT89M8MPu86382EPY6XJeAr2B+S0Jhz8fSEYzl1eblEddYeXE8RiYH8FOcHfIfxCSZL9Y45iekmlmmieqIfow6yPCG8pnl5EwKrlbkw5s64vDuFUVQVjZAD81NCm+sb600amz6DtXuWSojKg2DAq/RZxiCUbWn8AD732AWU2izB714npYhfDj8btCsuRcxqbAPaNmPaFqnvgUuxtL1NbiR1ioktc7eWx1wcyl1Y8Hq0kOOAqPWS7sGvDJ2Dz5OBnm6mdjOWpasD7udK232IaDaDz6Z5LYIVt/6RrapAk06utmRfzf6mr/0hXKqwEzbKSG6Y9BhVPKMO38uK8mwUlAhFbajJ78feEgeOFLIrH2a0dAUIv5ODml/WeGUu5wiHPWgMAOlIkqlJXMIIcMrLr7Q3Lsv3+zOtjDFnfmsz4PCha++rB5umSc29pkn7vUNT9NXXg4/lBnM9JN5pBEVs3RyUeuoG+N4kO8FoH0VNQo9Jeudpqf9sksw4kfnzy+OcITZftCMOwym5lw+6sDdk8ZMKrhQXIpUspRDG9pjkJ7or7aKAHs1/XqFvTUppy/eMEtiwN4XAfe6psxUFpQ9R/9xk2awoB8eODM+5oaV80kYpuMSnTqZ64DF/i2FBWnKCfMFs3hw3PfIvSxFLnryzNuobgL3mypCQHA+xshMqQU3xt2dDxdMScun1MWdU/yHGsfnW3CURfRRbNXKZM=
  template:
    metadata:
      name: secret-postgres-config
      namespace: exercises
