---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: exercises
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCvUuxoRVGs7ORVr71/AMOnV4GjE0sqsmhBpyC9clGHRgiRdOYnfv8mSdtAil8QROdg/L6zQtIyXtKSGQgIiFSSfAg7UZmGQY3HKH/+H7HFsFAyCByh6QTEDGDQ8bRI/d3DTdFXcH30KHjaK9OMccCLne3L5p5YbOUAr3TcjEHEw9wFDbe5a0UCUAQ2SARP68Xa2OiwqWeot8UrfrTAtSHY7ItWkfl4udWGH3nvrNc1Rbr0Oec0Jtutp74UUgSoh9wwZHxc/PEmeavm3OdL7pV+6fUbRungly95Fx1y/TNCfEPlT4AgRdObHvX1dVDH7RCdssckothJfrY2lMbUaN/98N1zWbpLzxDdkkK20Tnm7IEYUn92BE1sDenOFp5HXXkbhxuTrqbt8o6eQlG5VVykh4mt11GKyX10iZ+Ezpyyp/2a0BGtym9tyUEu7jjiq5V5R2xkkz29vEFSwwHJBsiEMtga0kK2opNOiUGctmOwZ35PhqV6ERZ/e/iDtDkjhrAft2lPq+5yfoj1gkmT6kr8osBG1sCOdvE1ZAIprb6i5pCgZJ5ga5/wVu6NxF051dmKn+mhRmiQqDQssr8xUql2QMNwL2H674GgZHRgsyDpiv4v7GN91tkaZdqV6FH3Ja1WG5pMUX0LXuPdbTF4OJ06tzAaFTJ4P1TSFxr0Qykj+YlraGWD8/+KTIiOuaEfi2Sgde0/ROpzpz5sYJk=
  template:
    metadata:
      name: secret-postgres-config
      namespace: exercises
