---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: exercises
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCo/S5zbp3eYC6xB0MC7RNidSM58OJIdSgtaSM/gZ4g22rbea2nzxhYoeogbxhQ9+eeSn0t25xTaGqILyxA0nCfeyHHRs4MWOScU/j1kfrdjJKYNGkWM4cHW8CJcjHaEtSF9ipdAfXGaUwQV7rUFhu66dzwzYUUVDtniet55NoUBMDGqPH11GOa9E+9zJsCh9rJeTFTjrbfIId003yNQkU08o9HOGGr10V2hZGDuyWbCFk2rnpbUrYn2Gsr4b6Q6+vQwWd8yNb0Ey4HoVnmpQxwWoGjo8YuMJY9A0U1c6w3PzbLMD36MvOuH1GzSk0SmeSJAUoh/QHb0QbGFvKNwi271NEdaioyNVuCEcjLtm91ny2y0YiF+J2hO3W2ZWarBlaYh9E02a/QcuZLLt267Rp2cgJyQjNsx80EyAP6rjDukVUClbDqPwjW/j4bh74f8uDYY4lk8nZdD2jwaAWdExMoBO01S8kDmXf7AEOjgYnncMG43hddeXZPpowbnpXZp8ZzRWZqk7exOqY6exiKGQBxN8M1rO01zM50MT4Oi8D6DH2qE9d66CIxxFsPj9DlLhgea1V4vm+yfqebbcz08ajhldS5fPKkjkjnA8wMkFBPS4gAg9yGicOVGeAtnHBpQJ7WaEkFU4iXJ4OX4pzY1ar0i8Tome3hPeYl6nMswp8Ax+ojU2Sy5kRoU1RYQJSlMjVNnJ6UO4PLsfely1E=
  template:
    metadata:
      name: secret-postgres-config
      namespace: exercises
