apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pingpongapp-svc
spec:
  type: ClusterIP
  selector:
    app: pingpongapp
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000