---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: project-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBVExPz1g7JvO5EZp93IC2LoDSUHtImkgpxXyaOAgulfDcDvQLkQ+2qwOeIcC3yFH/LGW/KGUoOev8mj/e+b/j3Bq3HbRDzyYvBPojlVr5RFGpMYqPVlZ8u6a8KAxShVPSasT1X0er2jrwcJ19O8he3MHk5tpA1IAtDJhoLZIdCOG0qo+YFpw/0EatR00Tyuvu/EWFkNgS5SmpTeb27rl+GgcxlA8zzysbw6CUmVyPHyN+VMyBxAh4puv0kAW206rCJk0T0vGVb1GryfmDW2R7i5y2L+kGXdeAQcfbSUGqgT0chiTtUZLLLkMtPsxlH2PxP10amCn0X+52wb+P8aYx1TGAA1az+xJZ68J6sFXPsJ9irGCmn/4lcDtS5kTY7aCM+eGkvdNMbsIGQg1qCQgeY1vs/YqdS9j05oPOYdSngjawf9fkD6ItVhqDtiHQlAG79NjdwxSQgt4oV0K9ynocrNplWXl2Wu3z42vd6PZf7cVk5MVTehcUwwqAwuo7edDXSGiRVqFLJeQbwYEKq1gfBivNx7JetXSb3UKlqjPMBroMle6fn2xxyYHsZN5Sg0JiCziBKAPOf0QC6sp+PHNkALUIWhGAZ9WXWZnma2QF87UJxCzmfUJxXr5vGh0tva9VNfqR8Q6ipNxZzNUjxdJXOn9raICAM/6aQOC/VofG4ui9CXvyBrifx7adykR6ZHusRC3ei20Odq+6fzaQ=
  template:
    metadata:
      name: secret-postgres-config
      namespace: project-staging
