---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: project-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBeR1kKjMNlnuAui3HWACeC52B4ROkl8nNO357P5/7L4NgtP+cZK2EuExxmZszUG0NEtX6sVJp21t36RPtsUxRYatlX/8DBui6x01b/ErKcZkNSuH8n4oYJn7f4954ZvEvNEK5rZIwc/OdRepzSeK7mtnodfyS+5+RUMhftSzLkJ2KeSe8G0SBzga2krSwyNNUQlyxMMXhOyzSJrChzYb1xWQlYXH8ZbKP13N7UOmFrVKfi/HEdmPK0pZVVkqVUVWiIKtDN/Xkn+A+KAuEGxH9FxKUbMesRIOFQ38jZbZ2r4389HovMh4ykObZc5VhDQ6l2SCM9a4TB3VsN0cfIIMmyPiVQmwDNDOc6YlLXQ+KseSV4AbWNy52lVQZV8ZucR441akelcvYlcKr7m0RW9CuL6Tz6iXe48NJuCFYt9wDB/LaCAik6sjnCFf8sDUjO5HpxLgMGT8ePFb/iKJkV/3Gz61RNySrkWzjniW+9qtforaopvgBrw/TQ7SjEJflMk0aVGq5GmUlst0h6DG2hs9njfhBjjx3iDc1I8/CRYdwL9TWA3Ou/dt9E3iFAK2yvwgP2EIYhVyS5PNp5BbpqXgzcfDdh/GCflRKJP2RaVsn3qzsdQZ0ZvJtgVJAZeqy3PuqizgcaYXP1+pyrop2qm2MO/a1MIr9M/3nyvHvjBoBFwT7TureD8Yr1bf0UeLKsfqnWXJDApwWomgvMDIU=
  template:
    metadata:
      name: secret-postgres-config
      namespace: project-staging
