name: 'Fetch Image'
description: 'Fetches existing image from repository or builds if not found and adds image to kustomization.yaml'
inputs:
  namespace:
    required: true
  image_name:
    required: true
  app_folder:
    required: true
  kustomization_folder:
    required: true
  build_folder:
    required: true
  image_alias:
    required: true
  build_arg_string:
    required: false

runs:
  using: "composite"
  steps:
    - name: Fetch existing image SHA
      id: 'sha'
      shell: bash
      run: |
        echo "image_sha=$(curl -s https://hub.docker.com/v2/namespaces/${{ inputs.namespace }}/repositories/${{ inputs.image_name }}/tags | jq '.results | sort_by(.last_pushed) | .[0].digest')" >> $GITHUB_OUTPUT

    - name: Build image if not found
      if: steps.sha.outputs.image_sha == ''
      uses: ./.github/actions/build_image
      with:
        namespace: "${{ inputs.namespace }}"
        image_name: "${{ inputs.image_name }}:${{ env.IMAGE_TAG }}"
        app_folder: "${{ inputs.app_folder }}"
        kustomization_folder: "${{ inputs.kustomization_folder }}"
        build_folder: "${{ inputs.build_folder }}"
        image_alias: "${{ inputs.image_alias }}"
        build_arg_string: "${{ inputs.build_arg_string }}"

    - name: Set found image
      if: steps.sha.outputs.image_sha != ''
      shell: bash
      working-directory: "${{ inputs.kustomization_folder }}"
      run: |
        IMAGE_PATH="${{ inputs.namespace }}/${{ inputs.image_name }}"
        kustomize edit set image "${{ inputs.image_alias }}"="$IMAGE_PATH@${{ steps.sha.outputs.image_sha }}"