---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: exercises
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB+bYVg1eI41n6IjNJF8EX+k9lXkhFrWSrdKan4IXBIJnfvcqFZF1lPAQExaBtDlwiJobUzHcGLU24D/6oDSMnarVekJB5AJ135D3EfLgft78q7ezp4szQ5wwf1/b+xRe6ZpFl7C5qDd8gbO3JOWx9wb8HKnaVON5psohqj7yuFEH6OaX08s2rk6ywTFdph53pEBsUcLFYjkw1KNPSLFkPnV8cARHRY0wilqYSkEBnTAcLTvtdqxyyq523u5X5OXPKlPb4eelWqlvBbpuYQNzic9APhERbVpXQZv5+AcpwRTXYIUeqpBmq6y1uPfuiEpQjklF+Il2hb3iy9cTjJI6BIVtgyI31164to6Wwj8phBC8vJyNKe/7AtYgYwZXmxukPRIDYQzYQmmZeMEVLCiGO7ZDJFuQZb8tE7tlPHQtc7T06eNCnXjLThfhnVUCdD4ioZehlH6dk2wwkRGmwb9eh8vz48ymAJftRql1s6O6s+InNK4AUH2GYu0Av/Ob2WViz3zZ+RBoI9H5bacyIeoXAOLM8qYuFQRxaMInZjsiqdVPhrIV0ijFWCAZvWuh604RVje6YoS8PC/2nFUaHiRcu8OxUfjOm+EPZA4Gax5ZDyHosbx/XU5IOD3ZYvRDz1v/dYVQXVEomd3kAVTfpfAeG5VTFHvlgDW45xBHhBCko1XMZsa5vpVqIz019foUwLdeWaHJLiAE2CW9nzCBw=
  template:
    metadata:
      name: secret-postgres-config
      namespace: exercises
