apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
# Seems to cause potential issues
# namePrefix: staging-
resources:
- resources/sealed_secret_postgres_staging.yaml
- resources/route_frontend_staging.yaml
- resources/route_backend_staging.yaml
- ./../../base
patches:
- path: patches/db_backup_job_staging.yaml
- path: patches/persistentvolumeclaim_todoapp_staging.yaml
- path: patches/configmap_todoapp_staging.yaml
images:
- digest: sha256:648a8b681f0e253f5f78688ab59939fff2cde3e33fca0f658bc70371cf9d682a
  name: PROJECT/BACKENDIMAGE
  newName: hinichijou/todo_app_backend-staging
- digest: sha256:b831f9abb8e9f930f4dd09f2ee4a8d582dfe40f25a55733be63ccb46eb0c0ded
  name: PROJECT/BROADCASTERIMAGE
  newName: hinichijou/broadcaster-staging
- digest: sha256:c9a16eadb92c69fb5a184432bfe4f02d84591185ff803e59fc91a97ee09b83bd
  name: PROJECT/DBBACKUPJOBIMAGE
  newName: hinichijou/db_backup_job-staging
- digest: sha256:d94d74fe5f493640c4134e97efeb694a1e78b2ce9c21724db218c3109491cd02
  name: PROJECT/FRONTENDIMAGE
  newName: hinichijou/todo_app_frontend-staging
- digest: sha256:13541ea45740f8c87a62e866d561575078592f1c8a9af30100259cb4a1398cf1
  name: PROJECT/WIKIPEDIATODOJOBIMAGE
  newName: hinichijou/wikipedia_todo_job-staging
