apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
# Seems to cause potential issues
# namePrefix: staging-
resources:
- resources/sealed_secret_postgres_staging.yaml
- resources/route_frontend_staging.yaml
- resources/route_backend_staging.yaml
- ./../../base
patches:
- path: patches/db_backup_job_staging.yaml
- path: patches/persistentvolumeclaim_todoapp_staging.yaml
- path: patches/configmap_todoapp_staging.yaml
images:
- digest: sha256:648a8b681f0e253f5f78688ab59939fff2cde3e33fca0f658bc70371cf9d682a
  name: PROJECT/BACKENDIMAGE
- digest: sha256:b831f9abb8e9f930f4dd09f2ee4a8d582dfe40f25a55733be63ccb46eb0c0ded
  name: PROJECT/BROADCASTERIMAGE
- digest: sha256:c9a16eadb92c69fb5a184432bfe4f02d84591185ff803e59fc91a97ee09b83bd
  name: PROJECT/DBBACKUPJOBIMAGE
  newName: hinichijou/db_backup_job-staging
- digest: sha256:ba856392a0e6686881706d4c787a89ef65e517e62dd3966507c7f6d794fca6d4
  name: PROJECT/FRONTENDIMAGE
- digest: sha256:4f06c09ed48ad4611895d657ada194ac2625440e29fb88e97f5a8a9bf78f5cde
  name: PROJECT/WIKIPEDIATODOJOBIMAGE
