apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
# Seems to cause potential issues
# namePrefix: staging-
resources:
- resources/sealed_secret_postgres_staging.yaml
- resources/route_frontend_staging.yaml
- resources/route_backend_staging.yaml
- ./../../base
patches:
- path: patches/db_backup_job_staging.yaml
- path: patches/persistentvolumeclaim_todoapp_staging.yaml
- path: patches/configmap_todoapp_staging.yaml
images:
- digest: sha256:b5a35754d57eda995326fb508f9630a830e0a45c1e34e4898176ff1c88129254
  name: PROJECT/BACKENDIMAGE
  newName: hinichijou/todo_app_backend-staging
- digest: sha256:c6d8ece4b4ae90957b04eb2f4fb098e4f5d8841b599057317da958c70715d59a
  name: PROJECT/BROADCASTERIMAGE
  newName: hinichijou/broadcaster-staging
- digest: sha256:e76e7b5777d5d744018ad5ccdcefd5586f09def7e0483d253b3e75ce1f010587
  name: PROJECT/DBBACKUPJOBIMAGE
  newName: hinichijou/db_backup_job-staging
  newTag: fb1ad38a5cd34d664e5ea55e86f73bcd8e64512f
- digest: sha256:b48d1fce718ff5a2857d11bdd26e9c1f319d20441743e89e4eeaf2e82b9a62fa
  name: PROJECT/FRONTENDIMAGE
  newName: hinichijou/todo_app_frontend-staging
- digest: sha256:a928777459f87c2998e01929a84a63fcd5c49189a7bf38c01f64b72988934882
  name: PROJECT/WIKIPEDIATODOJOBIMAGE
  newName: hinichijou/wikipedia_todo_job-staging
