---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: project-production
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC/H5VyZqLTyEi7LhT9MbYf40pnWq4/DblcCtY2E0j4X6zPWkKn6vOtm4pqrCv+mYiflwHH/UEdtYqrxfzEfrNQDs4cxT2uD3JrCSz4zdCpGmfDDPVSzI3EHTtXoYi6XJbiCfi4+T7mqGDQVtROsEBtAyjRX5cursryHXKNBvuT96cFDVypzgUcZT5DtwRUS3t0hPwiO0/Wz+VOCf91naTLXQaraU+2ROUba57s+/DslRpVZa6eEWJyKDk21KuWfGoVnP3RVgCLHOj4c9P5JyiOYO0OFlzUmEPrrDIUtybg/iYxI4pX/4NmrVkZGdfGlDpikiWHvJI0k0JPhfpY5FrBy53ZX9+iteJCMu8F326Fo/pAjBK4KwYUYH+I7LZ126X/+Rhb8j7g7QPKjp8y92oSnFxcIsbVQA4JVHKGrCFvuHFR1n0OAfA/4zNW2Q35cDPCiOZucYzjyhJj8/rnv3W0W0ep/D1VZx0musJjA0WdyT2rbV1q4iOWcqvF78xBWdjpttg/l4RgPPDFmfmz9+WrlPwNZYoTDVCDFzi2SOkVPaunh4UVcau540q/deVu2bSNTaNHJVilTIj09Z2ckIg9ZmXaIuENK1Tmi0q3g3SUHK0YO/jex1Oqm/TbnbCGuUepwS1TLZmSS1IonrOZwoVNaGImbMfq1n+74Lv5+q0tBQcZLR99jTaX+I9p5EqKwkqDzupOeyDyTFHeV/A=
  template:
    metadata:
      name: secret-postgres-config
      namespace: project-production
