---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret-postgres-config
  namespace: project-production
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBOizq58Eyd6McEVyRV7qKPp27p45PV7rxZznXdfReD/XavF1vdpBSLwDUU6E+yaWlDyXSeOUvz2y0kHctGQJ8wrzqjzdu9afCoO7cWiCm8KyEVQjfkIT1z3TvO2jCcfVpDBI+dkUJA+5X98LJV+5oNqsNa0Z4dKk1SqDXKYqsf7SXAfOOW9aR0rR273jdlk0pyKNx1Thl5xiQHbGyDpMSsx5pQ3oEna3pTCoOpYYsl0PNW5EvVGeOxCleES0bc6jcvs5QcorSyYTg3dRh0e8ZVaoYg7WunmSMZ8zdFXJ+wWsX3kYw76/kGBLyW0TRjs70wAp4iSQ8ELkPT7R81NvVSArXvfvBsc2IEWBaMO/FRipkBmIGtx04gUG79jRfxNdqj7JJ2kDshnkB64+RkG9bTLXDTRGDGCY6PfobUTHGudkcSBCt/IdqMLp1Q9+1XrZzi/bfI313xbebNh3+WcYxzAs+8Xd3geQ2MM3VYOlYAavhef0Vz6Zqm4Nwjcdzq8nQ5pIl5dwwLiOii0JWyPjLy5NcxyaihB52GK2oIor3/Hh50zw3I7iiI6HqS3w1XXews/lHHtEEfZUuTA2Vu8kI2BH76b3j7gLSNGfuWFTsFtjjpZDkYx5Gurj16UPk+AzJBuqXB7mVnFFweMpuOPuK96AR5NrprT8EGuS9DodfzVLsU1e7hRg8f8ZaRggeTqCgTvXMlucZ4cHm4iXI=
  template:
    metadata:
      name: secret-postgres-config
      namespace: project-production
