apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/envoy-gateway.yaml
  - manifests/istio-gateway.yaml
  - manifests/namespaces.yaml
  - manifests/persistentvolumes.yaml