# Finally we configure Grafana in grafana-values.yaml with Prometheus and Loki pre-wired as datasources,
# so both are available immediately after deployment without any manual setup.

adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prom-prometheus-server
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: "1"